sudo: required
services:
  - docker

before_install:
  - docker build -t bhanu/docker-react -f Dockerfile.dev .

script:
  - docker run bhanu/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  name: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-686814357902"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
           
